# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omp/proto/common.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16omp/proto/common.proto\x12\x19orbynt.memory.protocol.v1\"\x1a\n\x0b\x43\x61nonicalId\x12\x0b\n\x03uri\x18\x01 \x01(\t\"2\n\x0cNamespaceRef\x12\x14\n\x0cnamespace_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x9a\x02\n\nProvenance\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x12\n\ncreated_at\x18\x02 \x01(\t\x12\x12\n\nupdated_at\x18\x03 \x01(\t\x12\x11\n\tsource_id\x18\x04 \x01(\t\x12\x13\n\x0bsource_type\x18\x05 \x01(\t\x12\x14\n\x0csource_label\x18\x06 \x01(\t\x12\x18\n\x10\x61\x63quisition_time\x18\x07 \x01(\t\x12I\n\nattributes\x18\x08 \x03(\x0b\x32\x35.orbynt.memory.protocol.v1.Provenance.AttributesEntry\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"1\n\tTimeRange\x12\x12\n\nstart_time\x18\x01 \x01(\t\x12\x10\n\x08\x65nd_time\x18\x02 \x01(\t\"-\n\x08\x43hecksum\x12\x11\n\talgorithm\x18\x01 \x01(\t\x12\x0e\n\x06\x64igest\x18\x02 \x01(\x0c\"\xc6\x01\n\x0c\x45xportPolicy\x12\x14\n\x0c\x61llow_export\x18\x01 \x01(\x08\x12\x17\n\x0f\x61llowed_targets\x18\x02 \x03(\t\x12\x15\n\rredacted_tags\x18\x03 \x03(\t\x12\x1a\n\x12include_embeddings\x18\x04 \x01(\x08\x12\x15\n\rinclude_graph\x18\x05 \x01(\x08\x12\x1b\n\x13include_preferences\x18\x06 \x01(\x08\x12 \n\x18include_private_memories\x18\x07 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omp.proto.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROVENANCE_ATTRIBUTESENTRY']._loaded_options = None
  _globals['_PROVENANCE_ATTRIBUTESENTRY']._serialized_options = b'8\001'
  _globals['_CANONICALID']._serialized_start=53
  _globals['_CANONICALID']._serialized_end=79
  _globals['_NAMESPACEREF']._serialized_start=81
  _globals['_NAMESPACEREF']._serialized_end=131
  _globals['_PROVENANCE']._serialized_start=134
  _globals['_PROVENANCE']._serialized_end=416
  _globals['_PROVENANCE_ATTRIBUTESENTRY']._serialized_start=367
  _globals['_PROVENANCE_ATTRIBUTESENTRY']._serialized_end=416
  _globals['_TIMERANGE']._serialized_start=418
  _globals['_TIMERANGE']._serialized_end=467
  _globals['_CHECKSUM']._serialized_start=469
  _globals['_CHECKSUM']._serialized_end=514
  _globals['_EXPORTPOLICY']._serialized_start=517
  _globals['_EXPORTPOLICY']._serialized_end=715
# @@protoc_insertion_point(module_scope)

