# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omp/proto/embedding.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19omp/proto/embedding.proto\x12\x19orbynt.memory.protocol.v1\"V\n\x0e\x45mbeddingModel\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x12\n\ndimensions\x18\x04 \x01(\r\"r\n\x0f\x45mbeddingVector\x12\x14\n\x0c\x65mbedding_id\x18\x01 \x01(\t\x12\x11\n\tmemory_id\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12\x0e\n\x06values\x18\x04 \x03(\x02\x12\x14\n\x0c\x65xternal_ref\x18\x05 \x01(\t\"I\n\x0c\x45mbeddingRef\x12\x14\n\x0c\x65mbedding_id\x18\x01 \x01(\t\x12\x11\n\tmemory_id\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\"\x90\x01\n\x16\x45mbeddingIndexMetadata\x12\x39\n\x06models\x18\x01 \x03(\x0b\x32).orbynt.memory.protocol.v1.EmbeddingModel\x12;\n\x07vectors\x18\x02 \x03(\x0b\x32*.orbynt.memory.protocol.v1.EmbeddingVectorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omp.proto.embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDINGMODEL']._serialized_start=56
  _globals['_EMBEDDINGMODEL']._serialized_end=142
  _globals['_EMBEDDINGVECTOR']._serialized_start=144
  _globals['_EMBEDDINGVECTOR']._serialized_end=258
  _globals['_EMBEDDINGREF']._serialized_start=260
  _globals['_EMBEDDINGREF']._serialized_end=333
  _globals['_EMBEDDINGINDEXMETADATA']._serialized_start=336
  _globals['_EMBEDDINGINDEXMETADATA']._serialized_end=480
# @@protoc_insertion_point(module_scope)

