# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omp/proto/graph.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15omp/proto/graph.proto\x12\x19orbynt.memory.protocol.v1\">\n\tGraphNode\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tmemory_id\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\t\"\x93\x01\n\tGraphEdge\x12\x0f\n\x07\x65\x64ge_id\x18\x01 \x01(\t\x12\x18\n\x10source_memory_id\x18\x02 \x01(\t\x12\x18\n\x10target_memory_id\x18\x03 \x01(\t\x12\x31\n\x04kind\x18\x04 \x01(\x0e\x32#.orbynt.memory.protocol.v1.EdgeKind\x12\x0e\n\x06weight\x18\x05 \x01(\x02\"E\n\rMemoryCluster\x12\x12\n\ncluster_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\nmemory_ids\x18\x03 \x03(\t\"\xb3\x01\n\x0bMemoryGraph\x12\x33\n\x05nodes\x18\x01 \x03(\x0b\x32$.orbynt.memory.protocol.v1.GraphNode\x12\x33\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32$.orbynt.memory.protocol.v1.GraphEdge\x12:\n\x08\x63lusters\x18\x03 \x03(\x0b\x32(.orbynt.memory.protocol.v1.MemoryCluster*\xe5\x01\n\x08\x45\x64geKind\x12\x19\n\x15\x45\x44GE_KIND_UNSPECIFIED\x10\x00\x12\x18\n\x14\x45\x44GE_KIND_RELATES_TO\x10\x01\x12\x16\n\x12\x45\x44GE_KIND_SUPPORTS\x10\x02\x12\x19\n\x15\x45\x44GE_KIND_CONTRADICTS\x10\x03\x12\x18\n\x14\x45\x44GE_KIND_DEPENDS_ON\x10\x04\x12\x1a\n\x16\x45\x44GE_KIND_DERIVED_FROM\x10\x05\x12\x1d\n\x19\x45\x44GE_KIND_TEMPORAL_BEFORE\x10\x06\x12\x1c\n\x18\x45\x44GE_KIND_TEMPORAL_AFTER\x10\x07\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omp.proto.graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EDGEKIND']._serialized_start=520
  _globals['_EDGEKIND']._serialized_end=749
  _globals['_GRAPHNODE']._serialized_start=52
  _globals['_GRAPHNODE']._serialized_end=114
  _globals['_GRAPHEDGE']._serialized_start=117
  _globals['_GRAPHEDGE']._serialized_end=264
  _globals['_MEMORYCLUSTER']._serialized_start=266
  _globals['_MEMORYCLUSTER']._serialized_end=335
  _globals['_MEMORYGRAPH']._serialized_start=338
  _globals['_MEMORYGRAPH']._serialized_end=517
# @@protoc_insertion_point(module_scope)

