# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omp/proto/identity.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from omp.proto import common_pb2 as omp_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18omp/proto/identity.proto\x12\x19orbynt.memory.protocol.v1\x1a\x16omp/proto/common.proto\"\x89\x01\n\nPreference\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x39\n\nprovenance\x18\x05 \x01(\x0b\x32%.orbynt.memory.protocol.v1.Provenance\"N\n\x10PreferenceBundle\x12:\n\x0bpreferences\x18\x01 \x03(\x0b\x32%.orbynt.memory.protocol.v1.Preference\"\xb4\x01\n\x05Skill\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05level\x18\x03 \x01(\t\x12\x18\n\x10years_experience\x18\x04 \x01(\x02\x12\x10\n\x08\x65vidence\x18\x05 \x03(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x02\x12\x39\n\nprovenance\x18\x07 \x01(\x0b\x32%.orbynt.memory.protocol.v1.Provenance\"?\n\x0bSkillBundle\x12\x30\n\x06skills\x18\x01 \x03(\x0b\x32 .orbynt.memory.protocol.v1.Skill\"|\n\x08Interest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x39\n\nprovenance\x18\x04 \x01(\x0b\x32%.orbynt.memory.protocol.v1.Provenance\"H\n\x0eInterestBundle\x12\x36\n\tinterests\x18\x01 \x03(\x0b\x32#.orbynt.memory.protocol.v1.Interest\"\x92\x02\n\x0fIdentityProfile\x12\x13\n\x0bpassport_id\x18\x01 \x01(\t\x12\x13\n\x0bidentity_id\x18\x02 \x01(\t\x12\x14\n\x0c\x64isplay_name\x18\x03 \x01(\t\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x0f\n\x07\x61liases\x18\x05 \x03(\t\x12\x0e\n\x06locale\x18\x06 \x01(\t\x12\x10\n\x08timezone\x18\x07 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x08 \x01(\t\x12\x18\n\x10primary_language\x18\t \x01(\t\x12\x14\n\x0cnamespace_id\x18\n \x01(\t\x12\x39\n\nprovenance\x18\x0b \x01(\x0b\x32%.orbynt.memory.protocol.v1.Provenanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omp.proto.identity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PREFERENCE']._serialized_start=80
  _globals['_PREFERENCE']._serialized_end=217
  _globals['_PREFERENCEBUNDLE']._serialized_start=219
  _globals['_PREFERENCEBUNDLE']._serialized_end=297
  _globals['_SKILL']._serialized_start=300
  _globals['_SKILL']._serialized_end=480
  _globals['_SKILLBUNDLE']._serialized_start=482
  _globals['_SKILLBUNDLE']._serialized_end=545
  _globals['_INTEREST']._serialized_start=547
  _globals['_INTEREST']._serialized_end=671
  _globals['_INTERESTBUNDLE']._serialized_start=673
  _globals['_INTERESTBUNDLE']._serialized_end=745
  _globals['_IDENTITYPROFILE']._serialized_start=748
  _globals['_IDENTITYPROFILE']._serialized_end=1022
# @@protoc_insertion_point(module_scope)

