# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omp/proto/orb.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from omp.proto import common_pb2 as omp_dot_proto_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13omp/proto/orb.proto\x12\x19orbynt.memory.protocol.v1\x1a\x16omp/proto/common.proto\"\x9d\x01\n\x0f\x43hunkDescriptor\x12\x12\n\nchunk_type\x18\x01 \x01(\r\x12\x13\n\x0b\x63hunk_flags\x18\x02 \x01(\r\x12\x14\n\x0c\x63hunk_offset\x18\x03 \x01(\x04\x12\x14\n\x0c\x63hunk_length\x18\x04 \x01(\x04\x12\x35\n\x08\x63hecksum\x18\x05 \x01(\x0b\x32#.orbynt.memory.protocol.v1.Checksum\"c\n\x14OrbContainerMetadata\x12\x0f\n\x07version\x18\x01 \x01(\t\x12:\n\x06\x63hunks\x18\x02 \x03(\x0b\x32*.orbynt.memory.protocol.v1.ChunkDescriptor\"s\n\tOrbFooter\x12\x19\n\x11total_file_length\x18\x01 \x01(\x04\x12\x35\n\x08\x63hecksum\x18\x02 \x01(\x0b\x32#.orbynt.memory.protocol.v1.Checksum\x12\x14\n\x0c\x66ooter_magic\x18\x03 \x01(\x0c\"\x97\x01\n\x0cOrbContainer\x12\x41\n\x08metadata\x18\x01 \x01(\x0b\x32/.orbynt.memory.protocol.v1.OrbContainerMetadata\x12\x0e\n\x06\x63hunks\x18\x02 \x03(\x0c\x12\x34\n\x06\x66ooter\x18\x03 \x01(\x0b\x32$.orbynt.memory.protocol.v1.OrbFooterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omp.proto.orb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKDESCRIPTOR']._serialized_start=75
  _globals['_CHUNKDESCRIPTOR']._serialized_end=232
  _globals['_ORBCONTAINERMETADATA']._serialized_start=234
  _globals['_ORBCONTAINERMETADATA']._serialized_end=333
  _globals['_ORBFOOTER']._serialized_start=335
  _globals['_ORBFOOTER']._serialized_end=450
  _globals['_ORBCONTAINER']._serialized_start=453
  _globals['_ORBCONTAINER']._serialized_end=604
# @@protoc_insertion_point(module_scope)

