# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omp/proto/query.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from omp.proto import common_pb2 as omp_dot_proto_dot_common__pb2
from omp.proto import memory_pb2 as omp_dot_proto_dot_memory__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15omp/proto/query.proto\x12\x19orbynt.memory.protocol.v1\x1a\x16omp/proto/common.proto\x1a\x16omp/proto/memory.proto\"\xae\x01\n\x0bQueryFilter\x12;\n\x0cmemory_types\x18\x01 \x03(\x0e\x32%.orbynt.memory.protocol.v1.MemoryType\x12\x0c\n\x04tags\x18\x02 \x03(\t\x12\x38\n\ntime_range\x18\x03 \x01(\x0b\x32$.orbynt.memory.protocol.v1.TimeRange\x12\x1a\n\x12minimum_confidence\x18\x04 \x01(\x02\"\x95\x01\n\x0bMemoryQuery\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x36\n\x06\x66ilter\x18\x02 \x01(\x0b\x32&.orbynt.memory.protocol.v1.QueryFilter\x12\r\n\x05limit\x18\x03 \x01(\r\x12\x1a\n\x12include_embeddings\x18\x04 \x01(\x08\x12\x15\n\rinclude_graph\x18\x05 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omp.proto.query_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYFILTER']._serialized_start=101
  _globals['_QUERYFILTER']._serialized_end=275
  _globals['_MEMORYQUERY']._serialized_start=278
  _globals['_MEMORYQUERY']._serialized_end=427
# @@protoc_insertion_point(module_scope)

