# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omp/proto/registry.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18omp/proto/registry.proto\x12\x19orbynt.memory.protocol.v1\"b\n\x15\x43hunkTypeRegistration\x12\x12\n\nchunk_type\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rproto_message\x18\x03 \x01(\t\x12\x10\n\x08standard\x18\x04 \x01(\x08\"F\n\x12SchemaRegistration\x12\x0e\n\x06schema\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07package\x18\x03 \x01(\t\"W\n\x15NamespaceRegistration\x12\x14\n\x0cnamespace_id\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\t\x12\x19\n\x11\x61\x63\x63\x65ss_controlled\x18\x03 \x01(\x08\"\xdf\x01\n\x10RegistrySnapshot\x12\x45\n\x0b\x63hunk_types\x18\x01 \x03(\x0b\x32\x30.orbynt.memory.protocol.v1.ChunkTypeRegistration\x12>\n\x07schemas\x18\x02 \x03(\x0b\x32-.orbynt.memory.protocol.v1.SchemaRegistration\x12\x44\n\nnamespaces\x18\x03 \x03(\x0b\x32\x30.orbynt.memory.protocol.v1.NamespaceRegistrationb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omp.proto.registry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKTYPEREGISTRATION']._serialized_start=55
  _globals['_CHUNKTYPEREGISTRATION']._serialized_end=153
  _globals['_SCHEMAREGISTRATION']._serialized_start=155
  _globals['_SCHEMAREGISTRATION']._serialized_end=225
  _globals['_NAMESPACEREGISTRATION']._serialized_start=227
  _globals['_NAMESPACEREGISTRATION']._serialized_end=314
  _globals['_REGISTRYSNAPSHOT']._serialized_start=317
  _globals['_REGISTRYSNAPSHOT']._serialized_end=540
# @@protoc_insertion_point(module_scope)

