# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: omp/proto/response.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from omp.proto import memory_pb2 as omp_dot_proto_dot_memory__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18omp/proto/response.proto\x12\x19orbynt.memory.protocol.v1\x1a\x16omp/proto/memory.proto\"U\n\x0bMemoryMatch\x12\x37\n\x06memory\x18\x01 \x01(\x0b\x32\'.orbynt.memory.protocol.v1.MemoryRecord\x12\r\n\x05score\x18\x02 \x01(\x02\"I\n\x0eMemoryResponse\x12\x37\n\x07matches\x18\x01 \x03(\x0b\x32&.orbynt.memory.protocol.v1.MemoryMatch\".\n\rProtocolError\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omp.proto.response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMORYMATCH']._serialized_start=79
  _globals['_MEMORYMATCH']._serialized_end=164
  _globals['_MEMORYRESPONSE']._serialized_start=166
  _globals['_MEMORYRESPONSE']._serialized_end=239
  _globals['_PROTOCOLERROR']._serialized_start=241
  _globals['_PROTOCOLERROR']._serialized_end=287
# @@protoc_insertion_point(module_scope)

