PACKAGE_VERSION = "0.1.0"

PROTOCOL_MAJOR = 1
PROTOCOL_MINOR = 0
PROTOCOL_PATCH = 0
PROTOCOL_VERSION = f"{PROTOCOL_MAJOR}.{PROTOCOL_MINOR}.{PROTOCOL_PATCH}"

OPEN_TIER = "open"
OPEN_TIER_LABEL = "OPEN (unverified)"

